name: Deploy n8n Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy n8n to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull n8nio/n8n:latest
            docker stop n8n || true
            docker rm n8n || true
            docker volume create n8n_data || true
            docker run -d \
              --name n8n \
              --restart always \
              -p 5678:5678 \
              -e TZ=Etc/UTC \
              -v n8n_data:/home/node/.n8n \
              n8nio/n8n:latest
