---
- name: Install and Configure n8n using Docker
  hosts: all
  become: yes

  vars:
    n8n_domain: "{{ n8n_domain | default('localhost') }}"
    n8n_external_url: "{{ n8n_domain }}"
    n8n_home: "/n8n"
    n8n_timezone: "Etc/UTC"  # Change to your local timezone if needed

  tasks:
    - name: Install general prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: latest

    - name: Ensure Python Docker SDK is installed
      pip:
        name: docker
        state: present

    - name: Create persistent Docker volume for n8n
      command: docker volume create n8n_data
      args:
        creates: /var/lib/docker/volumes/n8n_data

    - name: Pull latest n8n Docker image
      docker_image:
        name: docker.n8n.io/n8nio/n8n
        source: pull
        tag: latest

    - name: Run n8n container
      docker_container:
        name: n8n
        image: docker.n8n.io/n8nio/n8n:latest
        state: started
        restart_policy: always
        ports:
          - "5678:5678"
        env:
          GENERIC_TIMEZONE: "{{ n8n_timezone }}"
          TZ: "{{ n8n_timezone }}"
          N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
          N8N_RUNNERS_ENABLED: "true"
        volumes:
          - "n8n_data:/home/node/.n8n"

    - name: Notify user of n8n startup
      debug:
        msg: |
          n8n is initializing. This may take a few minutes.
          Once ready, access it at http://{{ n8n_external_url }}:5678
