---
- name: Install and Configure n8n on Localhost using Docker
  hosts: localhost
  connection: local
  become: yes

  vars:
    n8n_home: "/n8n"
    n8n_timezone: "Etc/UTC"

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: latest

    - name: Install Python Docker SDK
      pip:
        name: docker
        state: present

    - name: Create Docker volume for n8n
      command: docker volume create n8n_data
      args:
        creates: /var/lib/docker/volumes/n8n_data

    - name: Pull n8n Docker image
      docker_image:
        name: n8nio/n8n:latest
        source: pull

    - name: Run n8n container
      docker_container:
        name: n8n
        image: n8nio/n8n:latest
        state: started
        restart_policy: always
        ports:
          - "5678:5678"
        env:
          TZ: "{{ n8n_timezone }}"
          GENERIC_TIMEZONE: "{{ n8n_timezone }}"
          N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
          N8N_RUNNERS_ENABLED: "true"
        volumes:
          - "n8n_data:/home/node/.n8n"

    - name: Notify user
      debug:
        msg: "n8n is now running on http://localhost:5678"
